AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Sample CloudFormation template with intentional errors
  for students to troubleshoot EC2 provisioning.

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The environment name (dev or prod).

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    Description: EC2 instance type.

  AMIId:
    Type: AWS::EC2::Image::Id
    Default: ami-029c5475368ac7adc
    Description: The AMI ID to use.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-instance"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: vpc-0295ba6c80998fff4
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref EC2Instance
